### ISSUE TITLE
TVManager *RecordingSize attributes should specify units

### ISSUE THREAD

**Issue by dbaron** [w3c/tvcontrol-api#18]
The [definitions](http://w3c.github.io/tvcontrol-api/#attributes-1) of totalRecordingSize and availableRecordingSize should say what units the results are in.  (Are they bytes?)

(I got here from https://github.com/w3ctag/spec-reviews/issues/111 .)

**Comment by chrisn** [comment]
Yes, I expect the units to be bytes (although I note that the [OIPF spec](http://www.oipf.tv/docs/OIPF-T1-R2_Specification-Volume-5-Declarative-Application-Environment-v2_3-2014-01-24.pdf) uses megabytes). Thank you for the review feedback; we've added issues here to track each item:

* Add examples to specification (#19)
* Parallel with WebRTC model (#20)
* Overlap between Media Recorder and Recorder APIs in TV Control (#21)
* Work with other groups to unify approaches to media streams (#22)
* Parental control PIN mechanism (#23)
* API surface and REST-based approach (#24)

**Comment by chrisn** [comment]
The units were specified as bytes in https://github.com/w3c/tvcontrol-api/commit/d93d1bdc04c527ca0a1532099671fa75908ef2ac.
