### ISSUE TITLE
Mapping of properties to service information

### ISSUE THREAD

**Issue by mprobst-irt** [w3c/tvcontrol-api#32]
More a question than a bug report.

Some of the API is generic other is specific for a broadcast system. If the spec includes also specific parameters, then I think it should define how service information is mapped on properties. 

For example how DVB SI descriptors map on the properties in the Channel and Programm objects. 

What is your opinion.

**Comment by chrisn** [comment]
Hi Michael. Thanks for your input. We already captured this issue in #10, so please continue the discussion there.
