### ISSUE TITLE
TVProgram#rating ?

### ISSUE THREAD

**Issue by mprobst-irt** [w3c/tvcontrol-api#34]
The description only says it is the rating of the channel which IMHO is not very helpful.

I assume it is parental rating stuff and not a user rating.

The current type is string, is that sufficient? OIPF DAE defines the parental rating as a collection of pairs of a parent scheme (e.g. DVB SI) and a specific value

**Comment by stevem-tw** [comment]
I've renamed this to parentalRating in my local copy of the spec.

**Comment by mprobst-irt** [comment]
thanks.
