### ISSUE TITLE
Abstract indicates IPTV is supported

### ISSUE THREAD

**Issue by paulhiggs** [w3c/tvcontrol-api#51]
The Abstract section says

> This specification defines an API for sourcing audio and video media, such as TV and radio from broadcast, IPTV

There is no mention of IPTV sources (normally identified by a unicast or multicast URL).

**Comment by stevem-tw** [comment]
This is an oversight.  I propose to add two new entries to the TVSourceType enum ("ip-multicast" and "ip-unicast") - is there anything else that we should add?

**Comment by paulhiggs** [comment]
I need to look at the model to see how this will work, but TVManager will need to accommodate 0..n multicast receiver/decoder instances. 
Some equivelant of a channel scan could occur, when invoked, some network server would be queried for an IP channel list (perhaps in DVB format)

**Comment by joaoserra** [comment]
It's not that simple...

What IP multicast really means in context of an IPTV service? An MPEG TS over raw UDP? MPEG TS Over RTP over UDP? 
What about DRM/CAS, and how to integrate it with W3C EME?
What about Fast Channel Change/Instant Channel Change techniques and retransmissons format? (RFCs 6285 and 4588)

About Unicast? What's unicast IPTV? RTSP? What about ABR formats? (i.e. DASH, HLS)? 

I think the IPTV case should be addressed as part of bigger discussion and not simply add types to the TVSourceType enum.

**Comment by tidoust** [comment]
Hi @joaoserra,

Thanks for your comments. I do not have concrete answers at this stage, but wanted to link them to open issues on our side. It would be useful if you could share scenarios and requirements that you would like to address.

> What IP multicast really means in context of an IPTV service? An MPEG TS over raw UDP? MPEG TS Over RTP over UDP?
> What about Fast Channel Change/Instant Channel Change techniques and retransmissons format? (RFCs 6285 and 4588)
> About Unicast? What's unicast IPTV? RTSP? What about ABR formats? (i.e. DASH, HLS)?

I do not think that the API should expose the complexity of the underlying transport mechanisms, unless you see a good reason to do so. That being said, the group does have in mind the need to address mappings to media delivery formats and protocols, in particular to make sure that the API can successfully handle that complexity, see: https://github.com/w3c/tvcontrol-api/issues/10

> What about DRM/CAS, and how to integrate it with W3C EME?

I raised a similar question some time ago: https://github.com/w3c/tvcontrol-api/issues/17

**Comment by paulhiggs** [comment]
Seems to be dead...
