### ISSUE TITLE
Use of TVSourceConstraints

### ISSUE THREAD

**Issue by paulhiggs** [w3c/tvcontrol-api#53]
The definition of [TVSourceConstraints ](https://www.w3.org/TR/tvcontrol-api/#tvsourceconstraints-dictionary)on 6.7 says 
>>TVSourceConstraints represents the list of constraints recognized by a User Agent for controlling the Capabilities of a TVSource object. This dictionary is used as a function return value, and never as an operation argument.

It is used as an argument to several functions so the second sentence is incorrect.
- TVManager.getSource(TVSourceConstraints constraints);
- TVManager.isSourceAvailable(TVSourceConstraints constraints);
- TVManager.getChannelList(TVSourceConstraints constraints);

**Comment by stevem-tw** [comment]
Well spotted!  Fixed in the latest commit.
